=== Leonardo-Cosmos/PseudoScript_Design/Assembly.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.pseudoscript.org/Assembly" xmlns:asm="http://www.pseudoscript.org/Assembly"
	elementFormDefault="qualified">

	<xsd:element name="assembly" type="asm:assembly"></xsd:element>

	<xsd:complexType name="assembly">
		<xsd:sequence>
			<xsd:element name="executor" type="asm:executor"
				maxOccurs="1" minOccurs="1">
			</xsd:element>
			<xsd:element name="operations">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="operation" type="asm:operation"
							maxOccurs="unbounded" minOccurs="0">
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="executor">
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="operation">
		<xsd:sequence>
			<xsd:element name="parameters">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="parameter" type="asm:parameter"
							maxOccurs="unbounded" minOccurs="0">
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="parameter">
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="defaultValue" type="xsd:string"
			use="optional"></xsd:attribute>
	</xsd:complexType>

</xsd:schema>

=== Leonardo-Cosmos/PseudoScript_Design/Assembly(Sample).xml
<?xml version="1.0" encoding="UTF-8"?>
<assembly xmlns="http://www.pseudoscript.org/Assembly"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.pseudoscript.org/Assembly Assembly.xsd">
	<executor name="Selenium"></executor>
	<operations>
		<operation name="OpenURL">
			<parameters>
				<parameter name="URL" type="string" />
			</parameters>
		</operation>
		<operation name="Click">
			<parameters>
				<parameter name="XPath" type="string" />
			</parameters>
		</operation>
		<operation name="InputText">
			<parameters>
				<parameter name="XPath" type="string" />
				<parameter name="Text" type="string" defaultValue="Sample" />
			</parameters>
		</operation>
	</operations>
</assembly>
